<a href="https://colab.research.google.com/github/BalaDharunesh/ml-for-python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy

In [3]:
import numpy as np

numpy vs list

In [5]:
from time import process_time

In [7]:
a=[1,2,3,4,5]
st=process_time()
a=[i+5 for i in a]
et=process_time()
print(et-st)

0.00010056099999999901


In [8]:
n=np.array([1,2,3,4,5])
st=process_time()
n+=5
et=process_time()
print(et-st)

0.00012558300000087286


print the numpy array and type

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


to find the dimension of array

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(5,)

In [6]:
c=np.array([(1,2,3),(1,2,3)])
print(c)
c.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

by mentioning the datatype

In [8]:
v=np.array([(1,2,3),(4,4,7)],dtype=float)
print(v)

[[1. 2. 3.]
 [4. 4. 7.]]


creating array of zeros

In [10]:
a=np.zeros((2,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]]


creating a array of ones

In [11]:
one=np.ones((2,3),dtype=int)
print(one)

[[1 1 1]
 [1 1 1]]


array of particular value

In [12]:
one=np.full((2,3),7)
print(one)

[[7 7 7]
 [7 7 7]]


creating identity matrix

In [13]:
i=np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


create a array of random values

In [14]:
a=np.random.random((3,4))
print(a)

[[0.52332032 0.94694424 0.84121129 0.40945556]
 [0.92772584 0.80186994 0.3875283  0.89713555]
 [0.49903416 0.36146319 0.06287547 0.16786588]]


create a array of random integer

In [18]:
r=np.random.randint(10,17,(3,5))
print(r)

[[12 13 12 13 12]
 [14 13 10 13 10]
 [14 14 13 15 15]]


to create a array with specified value

In [20]:
a=np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


array of values with steps specified

In [23]:
a=np.arange(10,30,5)
print(a)

[10 15 20 25]


list to array

In [24]:
a=[1,2,3,4]
arr=np.asarray(a)
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


analyze of array

In [25]:
a=np.random.randint(10,20,(5,5))
print(a)

[[14 15 14 19 16]
 [17 11 14 10 14]
 [12 17 17 15 15]
 [13 17 11 16 11]
 [12 17 17 15 17]]


shape,size,no of dimension and datatype

In [27]:
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

(5, 5)
25
2
int64


mathematicaal operation on numpy

in list

In [28]:
a=[1,2,3,4,5]
b=[1,8,6,7,7]
print(a+b) #concatenation of two list

[1, 2, 3, 4, 5, 1, 8, 6, 7, 7]


in numpy array

In [29]:
q=np.random.randint(0,10,(3,3))
p=np.random.randint(10,20,(3,3))
print(q+p)
print(q-p)
print(q*p)
print(q/p)

[[23 25 20]
 [15 19 27]
 [25 15 20]]
[[-11  -9  -4]
 [ -5 -17 -11]
 [ -7 -15  -4]]
[[102 136  96]
 [ 50  18 152]
 [144   0  96]]
[[0.35294118 0.47058824 0.66666667]
 [0.5        0.05555556 0.42105263]
 [0.5625     0.         0.66666667]]


another method for mathematical operation

In [30]:
q=np.random.randint(0,10,(3,3))
p=np.random.randint(10,20,(3,3))
print(np.add(q,p))
print(np.subtract(q,p))
print(np.multiply(q,p))
print(np.divide(q,p))

[[23 10 23]
 [14 17 23]
 [22 19 22]]
[[ -9 -10 -15]
 [ -6  -3  -5]
 [-12 -11 -10]]
[[112   0  76]
 [ 40  70 126]
 [ 85  60  96]]
[[0.4375     0.         0.21052632]
 [0.4        0.7        0.64285714]
 [0.29411765 0.26666667 0.375     ]]


array manipulation

In [33]:
q=np.random.randint(0,10,(3,2))
print(q)
print(np.transpose(q))

[[2 4]
 [9 0]
 [8 6]]
[[2 9 8]
 [4 0 6]]


another method

In [34]:
print(q.T)

[[2 9 8]
 [4 0 6]]


reshaping array

In [35]:
print(np.reshape(q,(2,3)))

[[2 4 9]
 [0 8 6]]
